### ISSUE TITLE
Saving best model based on which metric?

### ISSUE THREAD

**Issue by ehsan-soe** [ZhangShiyue/QGforQA#6]
Hi Shiyue,

Thanks for the nice job.
I realized from your code that for each checkpoint you are saving the best model based on BLEU score on validation set. Is that right?
Just wanted double check what is the metric you used to save the best model? BLEU or your own reward scores?

Thanks

**Comment by ZhangShiyue** [comment]
Yes, you are right. I save the best model based on the BLEU score.
